version: '1.0.0'

services:
  react-ui:
    build: ./react-ui
    container_name: react-ui
    environment:
      VITE_API_URL: "${VITE_API_URL}"
    ports:
      - "8082:5173"
    volumes:
      - ./react-ui:/app
      - /app/node_modules

  express-api:
    build: ./express-api
    container_name: express-api
    ports:
      - "8081:3010"
    env_file:
      - ./.env

  background-api:
    build: ./background-api
    container_name: background-api
    # ports:
    #   - ""
    env_file:
      - ./.env

  email-api:
    build: ./email-api
    container_name: email-api
    ports:
      - "8083:5239"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-ui
      - express-api

  db:
    image: postgres:16
    container_name: postgre_sql_db
    ports:
      - "8085:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin_ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRE_DB_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8086:80"

volumes:
  postgres_data: